site_name: Peter's Notebook
repo_url: https://github.com/peterleimbach/peterleimbach.github.io/
edit_uri: edit/main/docs/

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tooltips
    - content.code.copy
    - content.action.edit
  language: de  
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
  - git-revision-date-localized:
      enable_creation_date: true

nav:
- T1D:
    - Setup for Looping: setup-for-looping.md
    - Setup Redmi Note 13: setup-redmi-note-13.md
    - Cycling with AAPS: cycling-with-AAPS.md
    - Simple Charting DynISF: simple-charting-dynisf.md
- Linux:
    - Desktop: linux-desktop.md
    - SSH keys: generating-ssh-keys.md
- Markdown:
    - Resizing images: resizing-images.md
    - Setup mkdocs environment: setup-mkdocs-environment.md
