site_name: Peter's Notizbuch
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - admonition
  - pymdownx.details

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  language: de
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - search:
  - git-revision-date-localized:
      enable_creation_date: true

nav:
- Home:
    - index.md
- AndroidAPSDocs:
    - Tools: AndroidAAPSDocs-tools.md
    - Markdown: markdown.md
- T1D:
    - Sport with AAPS: making-sport-with-AAPS.md
- Linux:
    - Desktop: linux-desktop.md